Repository sunist-c/genius-invokation-simulator-backend, pull requests merged in 2023-01, with the labels that each got.

#11 Complete runtime rules design
  entity/card.go
  entity/character.go
  entity/player.go
  entity/rule.go
  main.go
  model/context/callback.go
Labels: enhancement

#12 Basically complete entity.core
  entity/character.go
  entity/core.go
  entity/player.go
  entity/rule.go
  enum/trigger.go
  main.go
  model/context/callback.go
  model/context/damage.go
Labels: enhancement

#14 Basically complete sync-message
  entity/core.go
  entity/player.go
  entity/rule.go
  enum/action.go
  enum/trigger.go
  exec/backend/main.go
  exec/cli/main.go
  main.go
  message/sync.go
  model/message/action.go
  model/message/sync.go
Labels: enhancement

#15 Basically complete framework.battle
  data/persistence/.gitignore
  entity/character.go
  entity/core.go
  entity/player.go
  entity/rule.go
  enum/player.go
  framework/battle.go
  main.go
  model/message/action.go
  model/message/initialize.go
  model/message/sync.go
  persistence/card.go
  persistence/character.go
  persistence/db.go
  persistence/player.go
  persistence/rule.go
  persistence/skill.go
Labels: enhancement

#17 Basically complete persistence and main logic
  entity/character.go
  entity/core.go
  entity/player.go
  entity/rule.go
  exec/backend/main.go
  exec/cli/main.go
  framework/battle.go
  go.mod
  main.go
  persistence/benchmark_test.go
  persistence/card.go
  persistence/character.go
  persistence/db.go
  persistence/model.go
  persistence/performance.go
  persistence/persistent.go
  persistence/player.go
  persistence/rule.go
  persistence/skill.go
  persistence/sqlite.go
  persistence/unit_test.go
Labels: enhancement

#18 Finish persistence module in #8, fix #16
  .drone.yml
  .github/workflows/go.yml
  data/.gitignore
  data/persistence/.gitignore
  data/persistence/.gitkeep
  enum/language.go
  enum/stage.go
  exec/backend/main.go
  exec/cli/main.go
  go.mod
  main.go
  model/localization/language.go
  model/message/sync.go
  persistence/db.go
  persistence/model.go
  protocol/http/engine.go
  protocol/http/middleware/qps.go
  protocol/http/middleware/uuid.go
  protocol/http/util/preprocess.go
  util/generate.go
Labels: bug, enhancement

#21 Fix sqlite3 errors, update http services
  persistence/db.go
  persistence/model.go
  persistence/sqlite.go
  protocol/http/config.go
  protocol/http/middleware/authenticator.go
  protocol/http/middleware/config.go
  protocol/http/service/carddeck.go
  protocol/http/service/player.go
Labels: bug, enhancement

#22 Clean working tree, update room-info services
  License
  exec/backend/main.go
  persistence/db.go
  persistence/interface.go
  persistence/model.go
  persistence/timing.go
  protocol/http/config/engine.go
  protocol/http/config/middleware.go
  protocol/http/config/service.go
  protocol/http/engine.go
  protocol/http/middleware/authenticator.go
  protocol/http/middleware/config.go
  protocol/http/middleware/interdictor.go
  protocol/http/middleware/qps.go
  protocol/http/middleware/trace.go
  protocol/http/middleware/uuid.go
  protocol/http/service/carddeck.go
  protocol/http/service/config.go
  protocol/http/service/init.go
  protocol/http/service/localization.go
  protocol/http/service/player.go
  protocol/http/service/roominfo.go
  readme.md
Labels: enhancement

#29 Basically complete the encapsulation of websocket.Connection
  entity/core.go
  entity/player.go
  enum/player.go
  enum/trigger.go
  framework/battle.go
  go.mod
  mod/adapter/event.go
  mod/adapter/mod.go
  mod/adapter/player.go
  mod/adapter/skill.go
  mod/adapter/summon.go
  mod/definition/event.go
  mod/definition/mod.go
  mod/definition/player.go
  mod/definition/skill.go
  mod/definition/summon.go
  model/adapter/adapter.go
  persistence/timing.go
  protocol/http/model/carddeck.go
  protocol/http/model/localization.go
  protocol/http/model/player.go
  protocol/http/service/carddeck.go
  protocol/http/service/localization.go
  protocol/http/service/player.go
  protocol/websocket/config/handler.go
  protocol/websocket/engine.go
  protocol/websocket/service/battle.go
  protocol/websocket/service/match.go
Labels: enhancement

#30 update document
  docs/_sidebar.md
  docs/development/api/README.md
  docs/development/api/card_deck.md
  docs/development/api/localization.md
  docs/development/api/player.md
  docs/en/_sidebar.md
  docs/index.html
Labels: documentation

#31 Restructured entity module
  entity/benchmark_test.go
  entity/card.go
  entity/character.go
  entity/core.go
  entity/model/card.go
  entity/model/cost.go
  entity/model/interface.go
  entity/model/rule.go
  entity/model/skill.go
  entity/player.go
  entity/unit_test.go
  framework/battle.go
  framework/event.go
  model/context/damage.go
  model/event/map.go
  model/event/set.go
  model/kv/map.go
  model/kv/ordered.go
  model/kv/unit_test.go
  model/modifier/chain.go
  persistence/model.go
  protocol/http/message/carddeck.go
  protocol/http/message/localization.go
  protocol/http/message/player.go
  protocol/http/service/carddeck.go
  protocol/http/service/localization.go
  protocol/http/service/player.go
  protocol/websocket/engine.go
  protocol/websocket/message/action.go
  protocol/websocket/message/initialize.go
  protocol/websocket/message/sync.go
  util/logger.go
Labels: enhancement

#32 为api文档进行了翻译
  docs/en/development/api/README.md
  docs/en/development/api/card_deck.md
  docs/en/development/api/localization.md
Labels: documentation
